const VALIDATION_ERROR_CODE = 400;
const UNAUTHORIZED_ERROR_CODE = 401;
const NOT_FOUND_CODE = 404;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  VALIDATION_ERROR_CODE,
  NOT_FOUND_CODE,
  UNAUTHORIZED_ERROR_CODE,
  DEFAULT_ERROR_CODE,
};
